# Generated by Django 4.1.7 on 2023-03-23 12:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApi', '0002_user_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=10),
        ),
    ]
