# Generated by Django 4.1.7 on 2023-03-23 12:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApi', '0006_remove_user_hash_remove_user_salt_alter_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=20),
        ),
    ]
